version: '3'

services:
    product_service:
        build: ./product_service
        volumes:
            - ./product_service:/home/node/app
        ports:
            - 5001:5000           
    front_web:
        image: node:lts-alpine
        user: "node"
        working_dir: /app
        volumes:
            - ./front_web:/app
        ports:
            - 5002:5000
        depends_on:
            - product_service
        command: "npm start"